version: '3.7'
services:
  gitlab-ee:
    image: 'gitlab/gitlab-ee:15.5.2-ee.0'
    restart: always
    hostname: 'viewtrixtech.loca.lt'
    container_name: gitlab-ee
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://viewtrixtech.loca.lt'
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    networks:
      - gitlab
    shm_size: '256m'
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner    
    restart: always
    depends_on:
      - gitlab-ee
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - './gitlab-runner:/etc/gitlab-runner'
    networks:
      - gitlab

networks:
  gitlab:
    name: gitlab-network
