version: '3.6'
services:
  jenkins:
    hostname: jenkins.example.com
    container_name: jenkins
    build: 
      context: .
      dockerfile: Dockerfile
    privileged: true
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock